local forester = require("forester")
local util = require("forester.util")
local scan = require("plenary.scandir")

describe("forester functions", function()
  describe("pad_addr", function()
    it("works", function()
      assert("0001" == util.pad_addr(1))
      assert("01TA" == util.pad_addr(2350))
    end)
  end)
  describe("next_addr", function()
    it("works", function()
      assert("foo-0002" == util.inc_addr("foo", 1))
      assert("foo-000A" == util.inc_addr("foo", 9))
      assert("foo-000F" == util.inc_addr("foo", 14))
      assert("foo-1000" == util.inc_addr("foo", 46655)) -- base36: ZZZ
    end)
  end)

  describe("prev_addr", function()
    it("works", function()
      assert("foo-0001" == util.decr_addr("foo", 2))
      assert("foo-0009" == util.decr_addr("foo", 10))
      assert("foo-000D" == util.decr_addr("foo", 14))
      assert("foo-0ZZY" == util.decr_addr("foo", 46655)) -- base36: ZZZ
    end)
  end)
end)
