local M = {}
-- Eventually this will be removed and become part of the LSP server
M.FORESTER_BUILTINS = {
  { label = "verb", documentation = "" },
  { label = "startverb", documentation = "" },
  { label = "scope", documentation = "" },
  { label = "put", documentation = "" },
  { label = "put?", documentation = "" },
  { label = "get", documentation = "" },
  {
    label = "import",
    documentation = "\\import{xxx-NNNN} brings the functions exported by the tree xxx-NNNN into scope ",
  },
  {
    label = "export",
    documentation = "\\export{xxx-NNNN} brings the functions exported by the tree xxx-NNNN into scope, and exports them from the current tree ",
  },
  { label = "namespace", documentation = "" },
  { label = "open", documentation = "" },
  { label = "def", documentation = "" },
  { label = "alloc", documentation = "" },
  { label = "subtree", documentation = "" },
  { label = "object", documentation = "" },
  { label = "patch", documentation = "" },
  { label = "call", documentation = "" },
  {
    label = "p",
    documentation = "creates a paragraph; unlike Markdown, it is mandatory to annotate paragraphs explicitly",
  },
  { label = "em", documentation = "typesets the content in italics" },
  { label = "strong", documentation = "typesets the content in boldface" },
  { label = "li", documentation = "creates a list item" },
  { label = "ol", documentation = "creates an ordered list" },
  { label = "ul", documentation = "creates an unordered list" },
  { label = "code", documentation = "typesets the content in monospace" },
  { label = "blockquote", documentation = "blockquote" },
  { label = "pre", documentation = "preformatted text" },
  { label = "figure", documentation = "" },
  { label = "figcaption", documentation = "" },
  { label = "transclude", documentation = "transclude a tree as a subsection" },
  { label = "tex", documentation = "" },
  { label = "ref", documentation = "" },
  { label = "title", documentation = "sets the title of the tree; can contain mainmatter markup" },
  {
    label = "taxon",
    documentation = "sets the taxon of the tree; example taxa include lemma, theorem, person, reference; the latter two taxa are treated specially by Forester for tracking biographical and bibliographical trees respectively",
  },
  { label = "date", documentation = "sets the creation date of the tree" },
  { label = "meta", documentation = "" },
  {
    label = "author",
    documentation = "\\author{name} sets the author of the tree to be the biographical tree at address name",
  },
  { label = "author/literal", documentation = "" },
  { label = "contributor", documentation = "" },
  { label = "contributor/literal", documentation = "" },
  { label = "parent", documentation = "" },
  { label = "number", documentation = "" },
  { label = "tag", documentation = "" },
  { label = "query", documentation = "" },
  { label = "query/rel", documentation = "" },
  { label = "query/rel/literal", documentation = "" },
  { label = "query/union", documentation = "" },
  { label = "query/isect", documentation = "" },
  { label = "query/isect-fam", documentation = "" },
  { label = "query/union-fam", documentation = "" },
  { label = "query/isect-fam-rel", documentation = "" },
  { label = "query/union-fam-rel", documentation = "" },
  { label = "query/compl", documentation = "" },
  { label = "query/tag", documentation = "" },
  { label = "query/taxon", documentation = "" },
  { label = "query/author", documentation = "" },
  { label = "query/author/literal", documentation = "" },
  { label = "query/incoming", documentation = "" },
  { label = "query/outgoing", documentation = "" },
  { label = "query/edges", documentation = "" },
  { label = "query/paths", documentation = "" },
  { label = "rel/tags", documentation = "" },
  { label = "rel/taxa", documentation = "" },
  { label = "rel/authors", documentation = "" },
  { label = "rel/contributors", documentation = "" },
  { label = "rel/transclusion", documentation = "" },
  { label = "rel/links", documentation = "" },
}

return M
