local forester = require("forester")
local util = require("util")
local scan = require("plenary.scandir")
local eq = assert.are.same

describe("forester functions", function()
  describe("pad_addr", function()
    it("works", function()
      eq("0001", forester.pad_addr(1))
      eq("01TA", forester.pad_addr(2350))
    end)
  end)
  describe("next_addr", function()
    it("works", function()
      eq("foo-0002", forester.inc_addr("foo", 1))
      eq("foo-000A", forester.inc_addr("foo", 9))
      eq("foo-000F", forester.inc_addr("foo", 14))
      eq("foo-1000", forester.inc_addr("foo", 46655)) -- base36: ZZZ
    end)
  end)

  describe("prev_addr", function()
    it("works", function()
      eq("foo-0001", forester.decr_addr("foo", 2))
      eq("foo-0009", forester.decr_addr("foo", 10))
      eq("foo-000D", forester.decr_addr("foo", 14))
      eq("foo-0ZZY", forester.decr_addr("foo", 46655)) -- base36: ZZZ
    end)
  end)
  describe("new_tree", function()
    it("works", function() end)
  end)
  describe("new_from_template", function()
    it("works", function() end)
  end)
  describe("open_tree", function()
    it("queries the forest", function()
      it("works", function() end)
      it("works", function() end)
    end)
  end)
  describe("transclude_new", function()
    it("works", function() end)
  end)
  describe("link_new", function()
    it("works", function() end)
  end)
end)
